<?php
$plugin = array(
 'title' => t('Three Rows Two Cols'),
 'category' => t('threerowthreecol'),
 'icon' => 'threerowthreecol.png',
 'theme' => 'threerowthreecol',
 'admin theme' => 'admin-threerowthreecol',
 'css' => 'threerowthreecol.css',
 'regions' => array(
  'top1' => t('Top 1'),
  'top2' => t('Top 2'),
  'top3' => t('Top 3'),
  'center' => t('Center'),
  'right' => t('Right side'),
  'left' => t('Left side')
 ),
);
