<?php
/**
 * @file
 * Add a simple field 'Phone'
 */

/**
 * Implements hook_form_alter().
 */
function dc_phone_field_form_alter(&$form, &$form_state, $form_id) {
 $defaultValue = '';
 if (isset($form['nid']['#value'])) {
  $defaultValue = _dc_phone_field_get_default_value_for_phone_field($form['nid']['#value']);
 }

 $form['phone_field'] = array(
  '#type' => 'textfield',
  '#title' => 'Phone: ',
  '#maxlenght' => 20,
  '#size' => 15,
  '#weight' => -10,
  '#default_value' => $defaultValue,
 );

}

/**
 * Implements hook_node_insert().
 */
function dc_phone_field_node_insert($node) {
 db_insert('sample_table')
  ->fields(array(
   'nid' => $node->nid,
   'value' => $node->phone_field,
  ))
  ->execute();
}

/**
 * Implements hook_node_update().
 */
function dc_phone_field_node_update($node) {
 db_update('sample_table')
  ->fields(array(
   'value' => $node->phone_field,
  ))
  ->condition('nid', $node->nid)
  ->execute();
}

/**
 * Implements hook_node_delete().
 */
function dc_phone_field_node_delete($node) {
 db_delete('sample_table')
  ->condition('nid', $node->nid)
  ->execute();
}

/**
 * Return value depending on nid from sample_table
 */
function _dc_phone_field_get_default_value_for_phone_field($nid) {
 $defaultValue = db_select('sample_table', 'st')
  ->fields('st', array('value'))
  ->condition('st.nid', $nid)
  ->execute()
  ->fetch();

 if (empty($defaultValue)) {
  return FALSE;
 }

 return $defaultValue->value;
}
