<?php
/**
 * @file
 * Show dropdown lists with countries and cities
 */

define('DC_PLACES_COUNTRIES_VID', 5);
define('DC_PLACES_CITIES_VID', 6);


/**
 * Implements hook_menu().
 */
function dc_places_menu() {
 $items['helloworld/places'] = array(
  'title' => 'Places',
  'description' => 'desc',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('dc_places_form'),
  'access callback' => TRUE,
  'type' => MENU_LOCAL_TASK,
 );

 $items['admin/config/places'] = array(
  'title' => 'Places configuration',
  'description' => 'Configure for places module',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('dc_places_admin_settings'),
  'file' => 'dc_places.admin.inc',
  'access callback' => TRUE,
  'weight' => 0,
 );

 $items['helloworld/showsettings'] = array(
  'title' => 'Show settings',
  'description' => 'desc',
  'page callback' => '_dc_places_get_setting_block',
  'access callback' => TRUE,
  'type' => MENU_LOCAL_TASK,
 );

 return $items;
}

/**
 * Implements hook_form().
 */
function dc_places_form($form, &$form_state) {
 $optionsCountries = _dc_places_get_countries();

 $selected = key($optionsCountries);
 if (isset($form_state['values']['countries'])){
  $selected = $form_state['values']['countries'];
 }

 $form['countries'] = array(
  '#type' => 'select',
  '#title' => 'Countries:',
  '#options' => $optionsCountries,
  '#ajax' => array(
   'callback' => '_dc_places_load_form_cities',
   'wrapper' => 'cities',
  ),
 );

 $form['cities'] = array(
  '#type' => 'select',
  '#title' => 'Cities:',
  '#prefix' => '<div id="cities">',
  '#suffix' => '</div>',
  '#options' => _dc_places_get_cities($selected),
 );

 return $form;
}

/**
 * Implements hook_block_info().
 */
function dc_places_block_info() {
 $block = array();
 $block['show_setting'] = array(
  'info' => t('Show settings!'),
 );

 return $block;
}

/**
 * Implements hook_block_view().
 */
function dc_places_block_view($delta = '') {
 $block = array();

 switch ($delta){
  case 'show_setting':
    $block['content'] = 'First Setting: '.variable_get('setting_first').'<br>Second Setting: '.variable_get('setting_second');
   break;
 }

 return $block;
}

/**
 * @return array list of country
 */
function _dc_places_get_countries() {
 $query = db_select('taxonomy_term_data', 't')
  ->fields('t', array('tid', 'name',))
  ->condition('vid', DC_PLACES_COUNTRIES_VID);
 $result = $query->execute()
  ->fetchAll();

 $countries = array();
 foreach ($result as $value) {
  $countries[$value->tid] = $value->name;
 }

 return $countries;
}

/**
 * @return array list of cities
 */
function _dc_places_get_cities($field_country_target_id) {
 $query = db_select('taxonomy_term_data', 'ttd');
 $query->innerJoin('field_data_field_country', 'fdfc', 'fdfc.entity_id = ttd.tid');
 $query->fields('ttd', array('tid', 'name'))
  ->condition('ttd.vid', DC_PLACES_CITIES_VID)
  ->condition('fdfc.field_country_target_id', $field_country_target_id);
 $result = $query->execute()
  ->fetchAll();
 $cities = array();
 foreach ($result as $value) {
  $cities[$value->tid] = $value->name;
 }
 
 return $cities;
}

/**
 *
 */
function _dc_places_load_form_cities($form, &$form_state) {
 return $form['cities'];
}

/**
 * 
 */
function _dc_places_get_setting_block() {
 $block = module_invoke('dc_places', 'block_view', 'show_setting');
 
 return render($block['content']);
}
