<?php

/**
 * @file
 * Show nodes
 */

/**
 * Implements hook_theme().
 */
function dc_show_nodes_theme($existing, $type, $theme, $path) {
 return array(
  'dc_custom_template' => array(
   'variables' => array(
    'data' => NULL,
   ),
   'template' => 'templates/dc_custom_template',
  )
 );
}

/**
 * Implements hook_menu().
 */
function dc_show_nodes_menu() {
 $items['helloworld/shownodes'] = array(
  'title' => 'Nodes',
  'description' => 'desc',
  'page callback' => '_dc_show_nodes_get_show_nodes_block',
  'access callback' => TRUE,
  'type' => MENU_LOCAL_TASK,
 );

 return $items;
}

/**
 * Implements hook_block_info().
 */
function dc_show_nodes_block_info() {
 $block = array();

 $block['show_nodes_block'] = array(
  'info' => t('Show Nodes!'),
 );

 return $block;
}

/**
 * Implements hook_block_view().
 */
function dc_show_nodes_block_view($delta = '') {
 $block = array();

 switch ($delta) {
  case 'show_nodes_block':
   $nidList = _dc_show_nodes_get_nodes_for_nodes_block();
   $nodes = node_load_multiple($nidList);

   $content = theme('dc_custom_template', array('data' => $nodes));

   $block = array(
    'subject' => t('Show Nodes Block'),
    'content' => $content,
   );
   break;
 }

 return $block;
}

/**
 *
 */
function _dc_show_nodes_get_show_nodes_block() {
 $block = module_invoke('dc_show_nodes', 'block_view', 'show_nodes_block');
 
 return render($block['content']);
}

/**
 *
 */
function _dc_show_nodes_get_nodes_for_nodes_block() {
 $query = db_select('node', 'n');

 $query->fields('n', array('nid'))
  ->condition('n.type', 'article')
  ->range(0, 5)
  ->orderBy('nid', 'DESC');

 $result = $query->execute()
  ->fetchAll();

 foreach ($result as $value) {
  $nidList[] = $value->nid;
 }
 
 return $nidList;
}
